<?php f::htmlStart(); ?>

<?php
f::plantillasUI($plantillas);
//f::message($plantillas);
foreach($plantillas['ruta'] as $i=> $ruta)
{
    ?>
    <div html_p__ruta="<?php echo f::encode('resource/plugin/'.$plantillas['ruta'][$i]); ?>" 
         style="float: left; margin: 3px;"
         class="ui-widget-content ui-corner-all classPadding5 mano classSelectUI">
        <div style="text-align: center">
            <?php echo $plantillas['carpeta'][$i]; ?>
        </div>
        <div class="classHeight5"></div>
        <div>
            <iframe class="classLoadIframeUI"
                    html_p__ruta="<?php echo base64_encode($plantillas['ruta'][$i]); ?>"
                    style="width: 150px; height: 130px" 
                    src="about:blank"  
                    scrolling="no"
                    frameborder="0"></iframe> 
        </div>
    </div>
    <?php
}
?> 

<?php f::htmlStop(); ?>