<?php f::htmlStart(); ?>
<?php
$oBL_Evacuacion=new BL_Evacuacion();
$form=$oBL_Evacuacion->getForm();
           
?>
<div class="ui-widget-content ui-corner-all ui-helper-clearfix classPadding5">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td align="right" 
                valign="middle"
                >
                Código CIP
            </td>
            <td align="center" valign="middle">:</td>
            <td align="left" valign="middle">
                <input type="text"  
                       class="ui-widget-content ui-corner-all" 
                       style="padding:5px;outline:none;width:256px;margin: 0px;" 
                       id="html_p__codCIP"
                       value="<?php echo $form[0]['codCIP'];?>"
                       />
            </td>
            <td></td>
            <td align="left" valign="middle">
                <div class="classRestaCaracteres ui-state-disabled">
                    <label class="html_p__codCIP"></label>
                </div>
            </td>
        </tr>
        <tr>
            <td align="center" valign="middle" style="width: 120px"><div class="classHeight5"></div></td>
            <td align="right" valign="middle" style="width: 10px"><?php f::pixel(10); ?></td>
            <td align="left" valign="middle" style="width: 256px"></td>
            <td align="right" valign="middle" style="width: 5px"><?php f::pixel(5); ?></td>
            <td align="left" valign="middle"><div class="classHeight5"></div></td>
        </tr>
        <tr>
            <td align="right" 
                valign="middle"
                >
                Lugar Origen
            </td>
            <td align="center" valign="middle">:</td>
            <td align="left" valign="middle">
                <input type="text"  
                       class="ui-widget-content ui-corner-all" 
                       style="padding:5px;outline:none;width:256px;margin: 0px;" 
                       id="html_p__lugarOrigen"
                       value="<?php echo $form[0]['lugarOrigen'];?>"
                       />
            </td>
            <td></td>
            <td align="left" valign="middle">
                <div class="classRestaCaracteres ui-state-disabled">
                    <label class="html_p__lugarOrigen"></label>
                </div>
            </td>
        </tr>
        <tr>
            <td><div class="classHeight5"></div></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td align="right" 
                valign="middle"
                >
                Lugar Destino
            </td>
            <td align="center" valign="middle">:</td>
            <td align="left" valign="middle">
                <input type="text"  
                       class="ui-widget-content ui-corner-all" 
                       style="padding:5px;outline:none;width:256px;margin: 0px;" 
                       id="html_p__lugarDestino"
                       value="<?php echo $form[0]['lugarDestino'];?>"
                       />
            </td>
            <td></td>
            <td align="left" valign="middle">
                <div class="classRestaCaracteres ui-state-disabled">
                    <label class="html_p__lugarDestino"></label>
                </div>
            </td>
        </tr>
        <tr>
            <td><div class="classHeight5"></div></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td align="right" 
                valign="middle" 
                >
                Motivo
            </td>
            <td align="center" valign="middle">:</td>
            <td align="left" valign="middle">

                <textarea class="ui-widget-content ui-corner-all" 
                          style="padding:5px;outline:none;width:256px;margin: 0px;" 
                          id="html_p__motivo"><?php echo $form[0]['motivo'];?></textarea> 
            </td>
            <td></td>
            <td align="left" valign="middle">
                <div class="classRestaCaracteres ui-state-disabled">
                    <label class="html_p__motivo"></label>
                </div>
            </td>
        </tr>
        <tr>
            <td><div class="classHeight5"></div></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td align="right" 
                valign="middle" 
                >
                Fecha Inicio
            </td>
            <td align="center" valign="middle">:</td>
            <td align="left" valign="middle">
                <input type="text"  
                       class="ui-widget-content ui-corner-all" 
                       style="padding:5px;outline:none;width:256px;margin: 0px;" 
                       id="html_p__fechaInicio"
                       value="<?php echo $form[0]['fechaInicio'];?>"
                       />
            </td>
            <td></td>
            <td align="left" valign="middle">
                <div class="classRestaCaracteres ui-state-disabled">
                    <label class="html_p__fechaInicio">yy-mm-dd</label>
                </div>
            </td>
        </tr>
        <tr>
            <td><div class="classHeight5"></div></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td align="right" 
                valign="middle" 
                >
                Fecha Fin
            </td>
            <td align="center" valign="middle">:</td>
            <td align="left" valign="middle">
                <input type="text"  
                       class="ui-widget-content ui-corner-all" 
                       style="padding:5px;outline:none;width:256px;margin: 0px;" 
                       id="html_p__fechaFin"
                       value="<?php echo $form[0]['fechaFin'];?>"
                       />
            </td>
            <td></td>
            <td align="left" valign="middle">
                <div class="classRestaCaracteres ui-state-disabled">
                    <label class="html_p__fechaFin">yy-mm-dd</label>
                </div>
            </td>
        </tr>
        <tr>
            <td><div class="classHeight5"></div></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td align="right" 
                valign="middle"
                >
                Observaciones
            </td>
            <td align="center" valign="middle">:</td>
            <td align="left" valign="middle">
                <textarea class="ui-widget-content ui-corner-all" 
                          style="padding:5px;outline:none;width:256px;margin: 0px;" 
                          id="html_p__observaciones"><?php echo $form[0]['observaciones'];?></textarea> 
            </td>
            <td></td>
            <td align="left" valign="middle">
                <div class="classRestaCaracteres ui-state-disabled">
                    <label class="html_p__observaciones"></label>
                </div>
            </td>
        </tr>
    </table>
    <div id="divMessageEvacuacion"></div>
    <input type="hidden" id="html_p__credencialEvacuacion" value="<?php echo f::encode(f::getCredencial()); ?>"/>
    <input type="hidden" id="html_p__codEvacuacion" value="<?php echo f::encode($form[0]['codEvacuacion']); ?>"/>
    
</div>
<?php f::htmlStop(); ?>