<?php f::htmlStart(); ?>
<?php
$oBL_Evacuacion=new BL_Evacuacion();
$table=$oBL_Evacuacion->lista();
?>
<table class="classTablaUI">
    <thead>
        <tr>
            <th>
                Codigo
            </th>
            <th>
                Nombres
            </th>
            <th>
                Grado
            </th>
            <th>
                Lugar Destino
            </th>
            <th style="text-align: center">
                <button class="buttonNuevoEvacuacion">Nuevo</button>
            </th>
        </tr>

        <tr class="classPaddinMargin0">
            <th class="classPaddinMargin0" style="width: 35px"></th>
            <th class="classPaddinMargin0" style="width: 50%"></th>
            <th class="classPaddinMargin0" style="width: 100px"></th>
            <th class="classPaddinMargin0" style="width: 50%"></th>
            <th class="classPaddinMargin0" style="width: 60px"><?php f::pixel(60); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        $codEvacuacion=s::get('codEvacuacion');
        foreach($table as $key=> $row)
        {
            if($row['codEvacuacion']==$codEvacuacion)
            {
                $class='ui-state-highlight';
            }
            else
            {
                $class='';
            }
            /*
              e.codEvacuacion
              , e.fecha
              , e.estado
              , e.lugarDestino
              , e.lugarOrigen
              , e.fechaInicio
              , e.fechaFin
              , e.motivo
              , e.observaciones
              , e.codPersonal
              , p.nombres
              , p.apellidoPat
              , p.apellidoMat
              , p.dni
              , p.edad
              , p.tipoSangre
              , p.grado
              , p.codCIP
             *  */
            ?>
        <tr html_p__codEvacuacion="<?php echo f::encode($row['codEvacuacion']) ?>" class="<?php echo $class;?>">
                <td>
                    <?php echo $row['codEvacuacion']; ?>
                </td>
                <td>
                    <?php echo $row['nombres'].' '.$row['apellidoPat'].' '.$row['apellidoMat']; ?>
                </td>
                <td>
                    <?php echo $row['grado']; ?>
                </td>
                <td>
                    <?php echo $row['lugarDestino']; ?>
                </td>
                <td style="text-align: center">
                    <button class="buttonEditarEvacucaion">Editar</button>
                    <button class="buttonEliminarEvacucaion">Eliminar</button>
                </td>
            </tr>
            <?php
        }
        ?>

    </tbody>
</table>
<?php f::htmlStop(); ?>