<?php f::htmlStart(); ?>
<?php
$oBL_Evacuacion=new BL_Evacuacion();
$table=$oBL_Evacuacion->listaEvcuaciones();
?>
<table class="classTablaUI">
    <thead>
        <tr>
            <th>
                Lugar Origen
            </th>
            <th>
                Lugar Destino
            </th>
            <th>
                Motivo
            </th>
            <th>
                Fechas
            </th>
            <th>
                Personal
            </th>
            <th>
                Estado
            </th>
        </tr>

        <tr class="classPaddinMargin0">
            <th class="classPaddinMargin0" style="width: 20%"></th>
            <th class="classPaddinMargin0" style="width: 20%"></th>
            <th class="classPaddinMargin0" style="width: 20%"></th>
            <th class="classPaddinMargin0" style="width: 150px"><?php f::pixel(150);?></th>
            <th class="classPaddinMargin0" style="width: 20%"></th>
            <th class="classPaddinMargin0" style="width: 20%"></th>
        </tr>
    </thead>
    <tbody>
        <?php 
        foreach($table as $key=> $row)
        { 
            /*
             e.codEvacuacion
                , e.fecha
                , e.estado
                , e.fechaInicio
                , e.fechaFin
                , e.motivo
                , e.observaciones
                , e.codPersonal
                , e.codTipoEvacuacion
                , e.codMedioEvacuacion
                , e.codPersonalAcompaniante
                , p.nombres
                , p.apellidoPat
                , p.apellidoMat
                , pa.nombres AS nombresAcompaniante
                , pa.apellidoPat AS apellidoPatAcompaniante
                , pa.apellidoMat AS apellidoMatAcompaniante
                , te.nombre AS motivo
                , me.nombre AS medioEvacuacion
                , u.nombre AS lugarOrigen
                , ud.nombre AS lugarDestino
             *  */
            switch($row['estado'])
            {
                case 1:
                    $row['estado']='Solicitado';
                    break;
                case 2:
                    $row['estado']='Aprobado';
                    break;
                case 3:
                    $row['estado']='Desaprobado';
                    break;
                default:
                    break;
            } 
            ?>
        <tr>
                <td>
                    <?php echo $row['lugarOrigen']; ?>
                </td>
                <td>
                    <?php echo $row['lugarDestino']; ?>
                </td>
                <td>
                    <?php echo $row['motivo']; ?>
                </td>
                <td>
                    <div>Registro: <?php echo date('m/d/Y',  strtotime($row['fecha'])); ?></div>
                    <div>Inicio: <?php echo date('m/d/Y',strtotime($row['fechaInicio'])); ?></div>
                    <div>Fin: <?php echo date('m/d/Y',strtotime($row['fechaFin'])); ?></div>
                </td>
                <td>
                    <?php echo $row['nombres'].' '.$row['apellidoPat'].' '.$row['apellidoMat']; ?>
                </td>
                <td>
                    <?php echo $row['estado']; ?>
                </td>
            </tr>
            <?php
        }
        ?>

    </tbody>
</table>
<?php f::htmlStop(); ?>