<?php f::htmlStart(); ?>
<?php
$oBL_Evacuacion=new BL_Evacuacion();
$motivos=$oBL_Evacuacion->listaMotivos();
$medioEvacuacion=$oBL_Evacuacion->listaMedioEvacuacion();
?>
<div class="ui-widget-content ui-corner-all ui-helper-clearfix classPadding5">
    Autorización de Evacuación
</div>
<div class="classHeight5"></div>
<div class="ui-widget-content ui-corner-all ui-helper-clearfix classPadding5">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td align="right" 
                valign="middle"
                style="width: 128px"
                >
                Buscar
                <?php f::pixel(128); ?>
            </td>
            <td align="center" valign="middle">
                :
                <?php f::pixel(10); ?>
            </td>
            <td align="left" valign="middle">
                <input type="text"  
                       class="ui-widget-content ui-corner-all ui-state-error" 
                       style="padding:5px;outline:none;width:256px;margin: 0px;" 
                       id="html_p__buscarPersonal"
                       />
            </td>
            <td align="right" valign="middle" style="width: 100%">
                Fecha de Creación: <?php echo date('d/m/Y'); ?>
            </td> 
        </tr>
    </table>
</div>
<div class="classHeight5"></div>
<div class="ui-widget-content ui-corner-all ui-helper-clearfix classPadding5">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td align="left" valign="top">
                <div class="ui-widget-content ui-corner-all ui-helper-clearfix classPadding5">
                    Datos Generales
                </div>
                <div class="classHeight5"><?php f::pixel(323) ?></div>
                <div class="ui-widget-content ui-corner-all ui-helper-clearfix classPadding5" style="min-height: 270px">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                            <td align="right" valign="middle">
                                Código CIP
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">
                                <div id="divResultadoRealizarEvacuacionCodigoCIP"
                                     class="ui-widget-content ui-corner-all  ui-state-disabled" 
                                     style="padding:5px;outline:none;width:156px;margin: 0px;" 
                                     >&nbsp;</div>
                            </td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td align="center" valign="middle" style="width: 128px"><div class="classHeight5"></div></td>
                            <td align="right" valign="middle" style="width: 10px"><?php f::pixel(10); ?></td>
                            <td align="left" valign="middle" style="width: 156px"></td>
                            <td align="right" valign="middle" style="width: 5px"><?php f::pixel(5); ?></td>
                            <td align="left" valign="middle"><div class="classHeight5"></div></td>
                        </tr>
                        <tr>
                            <td align="right" valign="middle">
                                Nombre
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">
                                <div id="divResultadoRealizarEvacuacionNombre"
                                     class="ui-widget-content ui-corner-all  ui-state-disabled" 
                                     style="padding:5px;outline:none;width:156px;margin: 0px;" 
                                     >&nbsp;</div>
                            </td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><div class="classHeight5"></div></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td align="right" valign="middle">
                                DNI
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">
                                <div id="divResultadoRealizarEvacuacionDNI"
                                     class="ui-widget-content ui-corner-all  ui-state-disabled" 
                                     style="padding:5px;outline:none;width:156px;margin: 0px;" 
                                     >&nbsp;</div>
                            </td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><div class="classHeight5"></div></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td align="right" valign="middle">
                                Edad
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">
                                <div id="divResultadoRealizarEvacuacionEdad"
                                     class="ui-widget-content ui-corner-all  ui-state-disabled" 
                                     style="padding:5px;outline:none;width:156px;margin: 0px;" 
                                     >&nbsp;</div>
                            </td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><div class="classHeight5"></div></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td align="right" valign="middle">
                                Lugar de Origen
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">
                                <div id="divResultadoRealizarEvacuacionLugarOrigen"
                                     class="ui-widget-content ui-corner-all  ui-state-disabled" 
                                     style="padding:5px;outline:none;width:156px;margin: 0px;" 
                                     >&nbsp;</div>
                            </td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><div class="classHeight5"></div></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td align="right" valign="middle">
                                Tipo Sangre
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">
                                <div id="divResultadoRealizarEvacuacionTipoSangre"
                                     class="ui-widget-content ui-corner-all  ui-state-disabled" 
                                     style="padding:5px;outline:none;width:156px;margin: 0px;" 
                                     >&nbsp;</div>
                            </td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><div class="classHeight5"></div></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td align="right" valign="middle">
                                Grado
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">
                                <div id="divResultadoRealizarEvacuacionGrado"
                                     class="ui-widget-content ui-coner-all ui-state-disabled" 
                                     style="padding:5px;outline:none;width:156px;margin: 0px;" 
                                     >&nbsp;</div>
                            </td>
                            <td></td>
                            <td></td>
                        </tr> 

                    </table>
                </div>
            </td>
            <td align="center" valign="middle"><?php f::pixel(5); ?></td>
            <td align="left" valign="top" style="width: 100%">
                <div class="ui-widget-content ui-corner-all ui-helper-clearfix classPadding5">
                    Datos Evacuación
                </div>
                <div class="classHeight5"></div>
                <div class="ui-widget-content ui-corner-all ui-helper-clearfix classPadding5" style="min-height: 270px">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0"> 
                        <tr>
                            <td align="right" 
                                valign="middle"
                                >
                                Lugar Destino
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">
                                <input type="text"  
                                       class="ui-widget-content ui-corner-all ui-state-error" 
                                       style="padding:5px;outline:none;width:256px;margin: 0px;" 
                                       id="html_p__buscarDestino" 
                                       />
                            </td>
                            <td></td>
                            <td align="left" valign="middle">
                                <div class="classRestaCaracteres ui-state-disabled">
                                    <label class="html_p__buscarDestino"></label>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" valign="middle" style="width: 150px"><div class="classHeight5"><?php f::pixel(150); ?></div></td>
                            <td align="right" valign="middle" style="width: 10px"><?php f::pixel(10); ?></td>
                            <td align="left" valign="middle" style="width: 256px"></td>
                            <td align="right" valign="middle" style="width: 5px"><?php f::pixel(5); ?></td>
                            <td align="left" valign="middle"><div class="classHeight5"></div></td>
                        </tr>
                        <tr>
                            <td align="right" 
                                valign="middle"
                                >
                                Motivo
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle"> 
                                <select
                                    class="ui-widget-content ui-corner-all" 
                                    style="padding:5px;outline:none;width:268px;margin: 0px;" 
                                    id="html_p__motivo" 
                                    >
                                    <option value="">--Seleccionar--</option>
                                    <?php
                                    foreach($motivos as $row)
                                    {
                                        ?>
                                        <option value="<?php echo f::encode($row['codTipoEvacuacion']); ?>">
                                            <?php echo $row['nombre']; ?>
                                        </option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </td>
                            <td></td>
                            <td align="left" valign="middle">
                                <div class="classRestaCaracteres ui-state-disabled">
                                    <label class=""></label>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td><div class="classHeight5"></div></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td align="right" 
                                valign="middle" 
                                >
                                Medio Evacuación
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">

                                <select
                                    class="ui-widget-content ui-corner-all" 
                                    style="padding:5px;outline:none;width:268px;margin: 0px;" 
                                    id="html_p__medioEvacuacion" 
                                    >
                                    <option value="">--Seleccionar--</option>
                                    <?php
                                    foreach($medioEvacuacion as $row)
                                    {
                                        ?>
                                        <option value="<?php echo f::encode($row['codMedioEvacuacion']); ?>">
                                            <?php echo $row['nombre']; ?>
                                        </option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </td>
                            <td></td>
                            <td align="left" valign="middle">
                                <div class="classRestaCaracteres ui-state-disabled">
                                    <label class=""></label>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td><div class="classHeight5"></div></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td align="right" 
                                valign="middle"
                                >
                                Personal Acompañante
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">
                                <input type="text"  
                                       class="ui-widget-content ui-corner-all ui-state-error" 
                                       style="padding:5px;outline:none;width:256px;margin: 0px;" 
                                       id="html_p__buscarPersonalAcompaniante" 
                                       />
                            </td>
                            <td></td>
                            <td align="left" valign="middle">
                                <div class="classRestaCaracteres ui-state-disabled">
                                    <label class="html_p__buscarPersonalAcompaniante"></label>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td><div class="classHeight5"></div></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td align="right" 
                                valign="middle" 
                                >
                                Fecha Inicio
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">
                                <input type="text"  
                                       readonly="readonly"
                                       class="ui-widget-content ui-corner-all" 
                                       style="padding:5px;outline:none;width:256px;margin: 0px;" 
                                       id="html_p__fechaInicio" 
                                       />
                            </td>
                            <td></td>
                            <td align="left" valign="middle">
                                <div class="classRestaCaracteres ui-state-disabled">
                                    <label class="html_p__fechaInicio">yy-mm-dd</label>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td><div class="classHeight5"></div></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td align="right" 
                                valign="middle" 
                                >
                                Fecha Fin
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">
                                <input type="text"
                                       readonly="readonly"
                                       class="ui-widget-content ui-corner-all" 
                                       style="padding:5px;outline:none;width:256px;margin: 0px;" 
                                       id="html_p__fechaFin" 
                                       />
                            </td>
                            <td></td>
                            <td align="left" valign="middle">
                                <div class="classRestaCaracteres ui-state-disabled">
                                    <label class="html_p__fechaFin">yy-mm-dd</label>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td><div class="classHeight5"></div></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td align="right" 
                                valign="middle"
                                >
                                Observaciones
                            </td>
                            <td align="center" valign="middle">:</td>
                            <td align="left" valign="middle">
                                <textarea class="ui-widget-content ui-corner-all" 
                                          style="padding:5px;outline:none;width:256px;margin: 0px;" 
                                          id="html_p__observaciones"></textarea> 
                            </td>
                            <td></td>
                            <td align="left" valign="middle">
                                <div class="classRestaCaracteres ui-state-disabled">
                                    <label class="html_p__observaciones"></label>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
    </table>
</div>
<div class="classHeight5"></div>
<div class="ui-widget-content ui-corner-all ui-helper-clearfix classPadding5" style="text-align: right">
    <button id="buttonRealizarEvacuacionGuardar">Guardar</button>
</div> 
<div id="divMessageRealizarEvacuacion"></div>
<input type="hidden" id="html_p__credencialRealizarEvacuacion" value="<?php echo f::encode(f::getCredencial()); ?>"/>

<?php f::htmlStop(); ?>