<?php f::htmlStart();?>

<?php
$oBL_Modulo=new BL_Modulo();
foreach($oBL_Modulo->listaModulos() as $i=> $row)
{
    if($i > 0)
    {
        ?>
        <div class="classHeight5"></div>
        <?php
    }
    ?> 
    <div html_p__idModulo="html_e__<?php echo $row['idModulo']; ?>"
         html_p__persistente="html_e__<?php echo $row['persistente']; ?>"
         style="font-weight: normal"
         class="ui-widget-content ui-corner-all classPadding5 classDivModulo mano">
             <?php echo $row['nombre']; ?>
    </div>
    <?php
}
?>
<input type="hidden" id="html_p__credencialLeftModulo" value="<?php echo f::encode(f::getCredencial()); ?>"/>
<?php f::htmlStop();?>