<?php f::htmlStart(); ?>
<?php
$oBL_Modulo=new BL_Modulo();
?>


<div class="ui-widget-content ui-corner-all classPadding5">
    <button class="classButtonAgregar">Agregar</button>
    <button class="classButtonAgregar">Editar</button>
    <button class="classButtonAgregar">Eliminar</button>
</div>

<div class="classHeight5"></div>

<table class="classTablaUI">
    <thead>
        <tr> 
            <th>
                Nro
            </th>
            <th>
                Modulo
            </th>
            <th>
                Descripcion
            </th>
            <th>
                Estado
            </th> 
        </tr>
        <tr class="classPaddinMargin0">
            <th class="classPaddinMargin0"><?php f::pixel(30); ?></th>
            <th class="classPaddinMargin0" style="width: 33%"></th>
            <th class="classPaddinMargin0" style="width: 33%"></th>
            <th class="classPaddinMargin0" style="width: 33%"></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach($oBL_Modulo->listaModulosPaginado() as $row)
        {
            ?>
            <tr>
                <td aling="left" valing="middle">
                    <?php echo $row['orden']; ?>
                </td>
                <td aling="left" valing="middle">
                    <div>
                        <strong><?php echo $row['nombre']; ?></strong>
                    </div>
                    <?php echo $row['descripcion']; ?>
                </td>
                <td aling="left" valing="middle">
                    <?php echo $row['estado']; ?>
                </td>
                <td aling="left" valing="middle">

                </td> 
            </tr>
            <?php
        }
        ?> 
    </tbody>
    <tfoot>
        <tr>
            <td aling="left" valing="middle" colspan="4">

            </td>
        </tr>
    </tfoot>
</table>
<?php f::htmlStop(); ?>