<div class="ui-overlay">
    <div class="ui-widget-overlay"></div>
</div>
<div class="divRecuoperarClaveFase3 ui-widget-content ui-corner-all ui-front ui-helper-clearfix" style="border-style: none">
    <div class="urp-marco">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td align="center" valign="middle">
                <div style="text-align:left">

                        <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
                            <tr>
                                <td align="left" valign="top">
                                    <div class="ui-widget-header ui-corner-all urp-titulo urp-texto-verde">
                                        Acceso Negado
                                    </div>
                                    
                                    <div class="urp-height-10"></div>
                                    <div class="urp-subrayado-continuo"></div>
                                    <div class="urp-height-10"></div>
                                    
                                    <div><label style="font-weight:bold">HostName:</label> <?php echo gethostbyaddr($_SERVER['REMOTE_ADDR']);?></div>
                                    <div><label style="font-weight:bold">IP:</label> <?php echo $_SERVER['REMOTE_ADDR'];?></div>
                                    <div><label style="font-weight:bold">Time:</label> <?php echo date("D M j G:i:s Y"); ?></div>
                                </td>
                            </tr>
                        </table>
                </div>
            </td>
        </tr>
    </table>
    </div>
</div>