<?php f::htmlStart(); ?>
<?php
$oBL_Archivamientoextends=new BL_Archivamientoextends();
$array_oGRID_Historia=$oBL_Archivamientoextends->lista();
?>
<table class="classTablaUI">
    <thead>
        <tr>
            <th>
                DNI
            </th>
            <th>
                Paciente
            </th>
            <th>
                Fecha
            </th>
            <th>
                Acción
            </th> 
        </tr>

        <tr class="classPaddinMargin0">
            <th class="classPaddinMargin0" style="width: 100px"></th> 
            <th class="classPaddinMargin0" ></th> 
            <th class="classPaddinMargin0" style="width: 100px"></th> 
            <th class="classPaddinMargin0" style="width: 40px"><?php f::pixel(40); ?></th> 
        </tr>
    </thead>
    <tbody>
        <?php
        foreach($array_oGRID_Historia as $oGRID_Historia)
        {
            $fechaActual=strtotime('-5 years', strtotime(date('Y-m-d')));
            $fechaUltimo=date('Y-m-d', strtotime($oGRID_Historia->get_ultimo()));
            if($fechaActual > $fechaUltimo)
            {
                $class='ui-state-highlight';
            }
            else
            {
                $class='';
            } 
            ?>
            <tr html_p__idPaciente="<?php echo f::encode($oGRID_Historia->get_idPaciente()) ?>" class="<?php echo $class; ?>">
                <td>
                    <?php echo $oGRID_Historia->get_dni(); ?>
                </td>
                <td>
                    <?php echo $oGRID_Historia->get_apellido(); ?>
                    <?php echo $oGRID_Historia->get_nombre(); ?>
                </td>
                <td>
                    <?php echo $fechaUltimo; ?>
                </td>
                 
                <td style="text-align: center">
                    <button class="classButtonArchivar">Archivar</button>
                </td> 
            </tr>
            <?php
        }
        ?>

    </tbody>
</table>
<input type="hidden" id="html_p__credencialAprobarEvacuacion" value="<?php echo f::encode(f::getCredencial()); ?>"/>
<?php f::htmlStop(); ?>